stages:
  - build
  - sync

variables:
  GIT_STRATEGY: clone
  GIT_DEPTH: 0
  GITHUB_ORG: vitalivu992
  GITEA_ORG: lvsoftwares

# Build stage - build the application
build:
  stage: build
  image: node:22
  cache:
    paths:
      - node_modules/
  before_script:
    - apt-get update && apt-get install -y python3 make g++
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - dist/
    expire_in: 1 hour
  only:
    - master

mirror_github:
  stage: sync
  image: ubuntu:latest
  before_script:
    - apt-get update && apt-get install -y git
    - git config --global user.email "linh.vuthai@gmail.com"
    - git config --global user.name "Linh Vu"
  script:
    - git remote add github https://$GITHUB_USERNAME:$GITHUB_TOKEN@github.com/$GITHUB_ORG/$CI_PROJECT_NAME.git || git remote set-url github https://$GITHUB_USERNAME:$GITHUB_TOKEN@github.com/$GITHUB_ORG/$CI_PROJECT_NAME.git
    - git checkout master
    - git pull --rebase github master
    - git push -u github master
    
  dependencies:
    - build
  only:
    - master

mirror_gitea:
  stage: sync
  image: ubuntu:latest
  before_script:
    - apt-get update && apt-get install -y git
    - git config --global user.email "linh.vuthai@gmail.com"
    - git config --global user.name "Linh Vu"
  script:
    - git remote add gitea $GITEA_TOKEN_URL/$GITEA_ORG/$CI_PROJECT_NAME.git || git remote set-url gitea $GITEA_TOKEN_URL/$GITEA_ORG/$CI_PROJECT_NAME.git
    - git checkout master
    - git pull --rebase gitea master
    - git push -u gitea master
    
  dependencies:
    - build
  only:
    - master